gpio ll wip
xEmbeddedTools/xmcu pull request #11
Opened 2024-10-03 11:11 UTC by msemegen

Changes related to GPIO LL implementation

2024-10-04 05:43 UTC, kaczirosan submitted a review, later dismissed

2024-10-04 05:43 UTC, kaczirosan commented on various.hpp
> -    // TODO: replace with std::to_underlying() when we migrate to cpp23 and gcc11+
Restore this comment

2024-10-04 05:57 UTC, kaczirosan requested changes

2024-10-04 05:57 UTC, kaczirosan commented on bit.hpp
> +    [[nodiscard]] constexpr static bool is(Register_t register_a, Index_t index_a)
index_a -> a_index or change coding standard

2024-10-07 15:58 UTC, msemegen commented on bit.hpp
> +    [[nodiscard]] constexpr static bool is(Register_t register_a, Index_t index_a)
yes, copy/paste from ng_hal

2024-10-07 15:58 UTC, msemegen commented on various.hpp
> -    // TODO: replace with std::to_underlying() when we migrate to cpp23 and gcc11+
yup

2024-10-08 10:11 UTC, msemegen commented on bit.hpp
> +    [[nodiscard]] constexpr static bool is(Register_t register_a, Index_t index_a)
done

2024-10-08 10:15 UTC, kaczirosan approved these changes

2024-10-08 10:18 UTC, merged